# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhX1PyszmHcxfdvgZDl-Mp_Aayqr_w44
"""

# Installing the AI brain and the web app tool
!pip install -q streamlit google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# 
# # Page Setup
# st.set_page_config(page_title="Ghost Recruiter Agent", layout="wide")
# st.title("👻 The Ghost Recruiter")
# st.markdown("### *Your Agentic AI Talent Agent*")
# 
# # Sidebar for the API Key
# with st.sidebar:
#     st.header("Settings")
#     api_key = st.text_input("Enter Gemini API Key:", type="password")
#     st.info("Built for HackAI @ LPU")
# 
# # Inputs
# col1, col2 = st.columns(2)
# with col1:
#     resume = st.text_area("📄 Step 1: Paste Resume", height=250)
# with col2:
#     jd = st.text_area("💼 Step 2: Paste Job Description", height=250)
# 
# # The 'Agentic' Action
# if st.button("🚀 ACTIVATE GHOST AGENT"):
#     if not api_key or not resume or not jd:
#         st.error("Please fill in all fields (API Key, Resume, and JD).")
#     else:
#         try:
#             genai.configure(api_key=api_key)
#             model = genai.GenerativeModel('gemini-2.5-flash')
# 
#             with st.status("Agent is making decisions...", expanded=True):
#                 st.write("Checking skills...")
#                 st.write("Calculating match score...")
# 
#                 # The instructions that make it 'Agentic'
#                 prompt = f"""
#                 Act as a 'Ghost Recruiter' Agent.
#                 Analyze this Resume: {resume}
#                 Against this JD: {jd}
#                 1. Give a Match Score (0-100%).
#                 2. Identify 3 Skills to learn (Decision).
#                 3. Write a pitch email focusing on the student's best project.
#                 """
#                 response = model.generate_content(prompt)
# 
#             st.success("Analysis Complete!")
#             st.markdown(response.text)
#             st.balloons()
#         except Exception as e:
#             st.error(f"Error: {e}")

# 1. Start the app in the background
!streamlit run app.py &>/content/logs.txt &

# 2. Open a window inside Colab to see your app
from google.colab import output
output.serve_kernel_port_as_iframe(8501, height='800')

# 1. Install the tool
!npm install -g localtunnel

# 2. Get your Password (needed for the link)
import urllib
print("COPY THIS PASSWORD:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# 3. Start the app and the link
!streamlit run app.py & npx localtunnel --port 8501